// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: command_queued.proto

package commandqueued

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandQueued struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceUdid  string `protobuf:"bytes,1,opt,name=device_udid,json=deviceUdid,proto3" json:"device_udid,omitempty"`
	CommandUuid string `protobuf:"bytes,2,opt,name=command_uuid,json=commandUuid,proto3" json:"command_uuid,omitempty"`
}

func (x *CommandQueued) Reset() {
	*x = CommandQueued{}
	if protoimpl.UnsafeEnabled {
		mi := &file_command_queued_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandQueued) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandQueued) ProtoMessage() {}

func (x *CommandQueued) ProtoReflect() protoreflect.Message {
	mi := &file_command_queued_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandQueued.ProtoReflect.Descriptor instead.
func (*CommandQueued) Descriptor() ([]byte, []int) {
	return file_command_queued_proto_rawDescGZIP(), []int{0}
}

func (x *CommandQueued) GetDeviceUdid() string {
	if x != nil {
		return x.DeviceUdid
	}
	return ""
}

func (x *CommandQueued) GetCommandUuid() string {
	if x != nil {
		return x.CommandUuid
	}
	return ""
}

var File_command_queued_proto protoreflect.FileDescriptor

var file_command_queued_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x71,
	0x75, 0x65, 0x75, 0x65, 0x64, 0x22, 0x53, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x75, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x55, 0x64, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x55, 0x75, 0x69, 0x64, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d, 0x64,
	0x6d, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d, 0x64, 0x6d, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x2f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_command_queued_proto_rawDescOnce sync.Once
	file_command_queued_proto_rawDescData = file_command_queued_proto_rawDesc
)

func file_command_queued_proto_rawDescGZIP() []byte {
	file_command_queued_proto_rawDescOnce.Do(func() {
		file_command_queued_proto_rawDescData = protoimpl.X.CompressGZIP(file_command_queued_proto_rawDescData)
	})
	return file_command_queued_proto_rawDescData
}

var file_command_queued_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_command_queued_proto_goTypes = []interface{}{
	(*CommandQueued)(nil), // 0: commandqueued.CommandQueued
}
var file_command_queued_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_command_queued_proto_init() }
func file_command_queued_proto_init() {
	if File_command_queued_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_command_queued_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandQueued); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_command_queued_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_command_queued_proto_goTypes,
		DependencyIndexes: file_command_queued_proto_depIdxs,
		MessageInfos:      file_command_queued_proto_msgTypes,
	}.Build()
	File_command_queued_proto = out.File
	file_command_queued_proto_rawDesc = nil
	file_command_queued_proto_goTypes = nil
	file_command_queued_proto_depIdxs = nil
}
