// Code generated by protoc-gen-go. DO NOT EDIT.
// source: command.proto

/*
Package commandproto is a generated protocol buffer package.

It is generated from these files:
	command.proto

It has these top-level messages:
	Event
	Payload
	Command
	ScheduleOSUpdate
	OSUpdate
	ScheduleOSUpdateScan
	AccountConfiguration
	AutoSetupAdminAccounts
	DeviceInformation
	InstallProfile
	RemoveProfile
	DeleteUser
	InstallApplication
	EraseDevice
	DeviceLock
	Settings
	Setting
	DeviceNameSetting
	HostnameSetting
*/
package commandproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Id           string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Time         int64    `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Payload      *Payload `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	DeviceUdid   string   `protobuf:"bytes,4,opt,name=device_udid,json=deviceUdid" json:"device_udid,omitempty"`
	PayloadBytes []byte   `protobuf:"bytes,5,opt,name=payload_bytes,json=payloadBytes,proto3" json:"payload_bytes,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Event) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Event) GetDeviceUdid() string {
	if m != nil {
		return m.DeviceUdid
	}
	return ""
}

func (m *Event) GetPayloadBytes() []byte {
	if m != nil {
		return m.PayloadBytes
	}
	return nil
}

type Payload struct {
	CommandUuid string   `protobuf:"bytes,1,opt,name=command_uuid,json=commandUuid" json:"command_uuid,omitempty"`
	Command     *Command `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
}

func (m *Payload) Reset()                    { *m = Payload{} }
func (m *Payload) String() string            { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()               {}
func (*Payload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Payload) GetCommandUuid() string {
	if m != nil {
		return m.CommandUuid
	}
	return ""
}

func (m *Payload) GetCommand() *Command {
	if m != nil {
		return m.Command
	}
	return nil
}

type Command struct {
	RequestType          string                `protobuf:"bytes,1,opt,name=request_type,json=requestType" json:"request_type,omitempty"`
	DeviceInformation    *DeviceInformation    `protobuf:"bytes,2,opt,name=device_information,json=deviceInformation" json:"device_information,omitempty"`
	InstallProfile       *InstallProfile       `protobuf:"bytes,3,opt,name=install_profile,json=installProfile" json:"install_profile,omitempty"`
	InstallApplication   *InstallApplication   `protobuf:"bytes,4,opt,name=install_application,json=installApplication" json:"install_application,omitempty"`
	AccountConfiguration *AccountConfiguration `protobuf:"bytes,5,opt,name=account_configuration,json=accountConfiguration" json:"account_configuration,omitempty"`
	ScheduleOsUpdate     *ScheduleOSUpdate     `protobuf:"bytes,6,opt,name=schedule_os_update,json=scheduleOsUpdate" json:"schedule_os_update,omitempty"`
	ScheduleOsUpdateScan *ScheduleOSUpdateScan `protobuf:"bytes,7,opt,name=schedule_os_update_scan,json=scheduleOsUpdateScan" json:"schedule_os_update_scan,omitempty"`
	RemoveProfile        *RemoveProfile        `protobuf:"bytes,8,opt,name=remove_profile,json=removeProfile" json:"remove_profile,omitempty"`
	DeleteUser           *DeleteUser           `protobuf:"bytes,9,opt,name=delete_user,json=deleteUser" json:"delete_user,omitempty"`
	Settings             *Settings             `protobuf:"bytes,10,opt,name=settings" json:"settings,omitempty"`
	EraseDevice          *EraseDevice          `protobuf:"bytes,11,opt,name=erase_device,json=eraseDevice" json:"erase_device,omitempty"`
	DeviceLock           *DeviceLock           `protobuf:"bytes,12,opt,name=device_lock,json=deviceLock" json:"device_lock,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Command) GetRequestType() string {
	if m != nil {
		return m.RequestType
	}
	return ""
}

func (m *Command) GetDeviceInformation() *DeviceInformation {
	if m != nil {
		return m.DeviceInformation
	}
	return nil
}

func (m *Command) GetInstallProfile() *InstallProfile {
	if m != nil {
		return m.InstallProfile
	}
	return nil
}

func (m *Command) GetInstallApplication() *InstallApplication {
	if m != nil {
		return m.InstallApplication
	}
	return nil
}

func (m *Command) GetAccountConfiguration() *AccountConfiguration {
	if m != nil {
		return m.AccountConfiguration
	}
	return nil
}

func (m *Command) GetScheduleOsUpdate() *ScheduleOSUpdate {
	if m != nil {
		return m.ScheduleOsUpdate
	}
	return nil
}

func (m *Command) GetScheduleOsUpdateScan() *ScheduleOSUpdateScan {
	if m != nil {
		return m.ScheduleOsUpdateScan
	}
	return nil
}

func (m *Command) GetRemoveProfile() *RemoveProfile {
	if m != nil {
		return m.RemoveProfile
	}
	return nil
}

func (m *Command) GetDeleteUser() *DeleteUser {
	if m != nil {
		return m.DeleteUser
	}
	return nil
}

func (m *Command) GetSettings() *Settings {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *Command) GetEraseDevice() *EraseDevice {
	if m != nil {
		return m.EraseDevice
	}
	return nil
}

func (m *Command) GetDeviceLock() *DeviceLock {
	if m != nil {
		return m.DeviceLock
	}
	return nil
}

type ScheduleOSUpdate struct {
	Updates []*OSUpdate `protobuf:"bytes,1,rep,name=updates" json:"updates,omitempty"`
}

func (m *ScheduleOSUpdate) Reset()                    { *m = ScheduleOSUpdate{} }
func (m *ScheduleOSUpdate) String() string            { return proto.CompactTextString(m) }
func (*ScheduleOSUpdate) ProtoMessage()               {}
func (*ScheduleOSUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ScheduleOSUpdate) GetUpdates() []*OSUpdate {
	if m != nil {
		return m.Updates
	}
	return nil
}

type OSUpdate struct {
	ProductKey    string `protobuf:"bytes,1,opt,name=product_key,json=productKey" json:"product_key,omitempty"`
	InstallAction string `protobuf:"bytes,2,opt,name=install_action,json=installAction" json:"install_action,omitempty"`
}

func (m *OSUpdate) Reset()                    { *m = OSUpdate{} }
func (m *OSUpdate) String() string            { return proto.CompactTextString(m) }
func (*OSUpdate) ProtoMessage()               {}
func (*OSUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *OSUpdate) GetProductKey() string {
	if m != nil {
		return m.ProductKey
	}
	return ""
}

func (m *OSUpdate) GetInstallAction() string {
	if m != nil {
		return m.InstallAction
	}
	return ""
}

type ScheduleOSUpdateScan struct {
	Force bool `protobuf:"varint,1,opt,name=force" json:"force,omitempty"`
}

func (m *ScheduleOSUpdateScan) Reset()                    { *m = ScheduleOSUpdateScan{} }
func (m *ScheduleOSUpdateScan) String() string            { return proto.CompactTextString(m) }
func (*ScheduleOSUpdateScan) ProtoMessage()               {}
func (*ScheduleOSUpdateScan) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ScheduleOSUpdateScan) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type AccountConfiguration struct {
	SkipPrimarySetupAccountCreation     bool                      `protobuf:"varint,1,opt,name=skip_primary_setup_account_creation,json=skipPrimarySetupAccountCreation" json:"skip_primary_setup_account_creation,omitempty"`
	SetPrimarySetupAccountAsRegularUser bool                      `protobuf:"varint,2,opt,name=set_primary_setup_account_as_regular_user,json=setPrimarySetupAccountAsRegularUser" json:"set_primary_setup_account_as_regular_user,omitempty"`
	AutoSetupAdminAccounts              []*AutoSetupAdminAccounts `protobuf:"bytes,3,rep,name=auto_setup_admin_accounts,json=autoSetupAdminAccounts" json:"auto_setup_admin_accounts,omitempty"`
}

func (m *AccountConfiguration) Reset()                    { *m = AccountConfiguration{} }
func (m *AccountConfiguration) String() string            { return proto.CompactTextString(m) }
func (*AccountConfiguration) ProtoMessage()               {}
func (*AccountConfiguration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AccountConfiguration) GetSkipPrimarySetupAccountCreation() bool {
	if m != nil {
		return m.SkipPrimarySetupAccountCreation
	}
	return false
}

func (m *AccountConfiguration) GetSetPrimarySetupAccountAsRegularUser() bool {
	if m != nil {
		return m.SetPrimarySetupAccountAsRegularUser
	}
	return false
}

func (m *AccountConfiguration) GetAutoSetupAdminAccounts() []*AutoSetupAdminAccounts {
	if m != nil {
		return m.AutoSetupAdminAccounts
	}
	return nil
}

type AutoSetupAdminAccounts struct {
	ShortName    string `protobuf:"bytes,1,opt,name=short_name,json=shortName" json:"short_name,omitempty"`
	FullName     string `protobuf:"bytes,2,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	PasswordHash []byte `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Hidden       bool   `protobuf:"varint,4,opt,name=hidden" json:"hidden,omitempty"`
}

func (m *AutoSetupAdminAccounts) Reset()                    { *m = AutoSetupAdminAccounts{} }
func (m *AutoSetupAdminAccounts) String() string            { return proto.CompactTextString(m) }
func (*AutoSetupAdminAccounts) ProtoMessage()               {}
func (*AutoSetupAdminAccounts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *AutoSetupAdminAccounts) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *AutoSetupAdminAccounts) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *AutoSetupAdminAccounts) GetPasswordHash() []byte {
	if m != nil {
		return m.PasswordHash
	}
	return nil
}

func (m *AutoSetupAdminAccounts) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

type DeviceInformation struct {
	Queries []string `protobuf:"bytes,1,rep,name=queries" json:"queries,omitempty"`
}

func (m *DeviceInformation) Reset()                    { *m = DeviceInformation{} }
func (m *DeviceInformation) String() string            { return proto.CompactTextString(m) }
func (*DeviceInformation) ProtoMessage()               {}
func (*DeviceInformation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeviceInformation) GetQueries() []string {
	if m != nil {
		return m.Queries
	}
	return nil
}

type InstallProfile struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *InstallProfile) Reset()                    { *m = InstallProfile{} }
func (m *InstallProfile) String() string            { return proto.CompactTextString(m) }
func (*InstallProfile) ProtoMessage()               {}
func (*InstallProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *InstallProfile) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type RemoveProfile struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
}

func (m *RemoveProfile) Reset()                    { *m = RemoveProfile{} }
func (m *RemoveProfile) String() string            { return proto.CompactTextString(m) }
func (*RemoveProfile) ProtoMessage()               {}
func (*RemoveProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *RemoveProfile) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type DeleteUser struct {
	Username      string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	ForceDeletion bool   `protobuf:"varint,2,opt,name=force_deletion,json=forceDeletion" json:"force_deletion,omitempty"`
}

func (m *DeleteUser) Reset()                    { *m = DeleteUser{} }
func (m *DeleteUser) String() string            { return proto.CompactTextString(m) }
func (*DeleteUser) ProtoMessage()               {}
func (*DeleteUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DeleteUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *DeleteUser) GetForceDeletion() bool {
	if m != nil {
		return m.ForceDeletion
	}
	return false
}

type InstallApplication struct {
	ItunesStoreId         int64  `protobuf:"varint,1,opt,name=itunes_store_id,json=itunesStoreId" json:"itunes_store_id,omitempty"`
	Identifier            string `protobuf:"bytes,2,opt,name=identifier" json:"identifier,omitempty"`
	ManifestUrl           string `protobuf:"bytes,3,opt,name=manifest_url,json=manifestUrl" json:"manifest_url,omitempty"`
	ManagementFlags       int64  `protobuf:"varint,4,opt,name=management_flags,json=managementFlags" json:"management_flags,omitempty"`
	NotManaged            bool   `protobuf:"varint,5,opt,name=not_managed,json=notManaged" json:"not_managed,omitempty"`
	ChangeManagementState string `protobuf:"bytes,6,opt,name=change_management_state,json=changeManagementState" json:"change_management_state,omitempty"`
}

func (m *InstallApplication) Reset()                    { *m = InstallApplication{} }
func (m *InstallApplication) String() string            { return proto.CompactTextString(m) }
func (*InstallApplication) ProtoMessage()               {}
func (*InstallApplication) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *InstallApplication) GetItunesStoreId() int64 {
	if m != nil {
		return m.ItunesStoreId
	}
	return 0
}

func (m *InstallApplication) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *InstallApplication) GetManifestUrl() string {
	if m != nil {
		return m.ManifestUrl
	}
	return ""
}

func (m *InstallApplication) GetManagementFlags() int64 {
	if m != nil {
		return m.ManagementFlags
	}
	return 0
}

func (m *InstallApplication) GetNotManaged() bool {
	if m != nil {
		return m.NotManaged
	}
	return false
}

func (m *InstallApplication) GetChangeManagementState() string {
	if m != nil {
		return m.ChangeManagementState
	}
	return ""
}

type EraseDevice struct {
	Pin              string `protobuf:"bytes,1,opt,name=pin" json:"pin,omitempty"`
	PreserveDataPlan bool   `protobuf:"varint,2,opt,name=preserve_data_plan,json=preserveDataPlan" json:"preserve_data_plan,omitempty"`
}

func (m *EraseDevice) Reset()                    { *m = EraseDevice{} }
func (m *EraseDevice) String() string            { return proto.CompactTextString(m) }
func (*EraseDevice) ProtoMessage()               {}
func (*EraseDevice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *EraseDevice) GetPin() string {
	if m != nil {
		return m.Pin
	}
	return ""
}

func (m *EraseDevice) GetPreserveDataPlan() bool {
	if m != nil {
		return m.PreserveDataPlan
	}
	return false
}

type DeviceLock struct {
	Pin         string `protobuf:"bytes,1,opt,name=pin" json:"pin,omitempty"`
	Message     string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	PhoneNumber string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
}

func (m *DeviceLock) Reset()                    { *m = DeviceLock{} }
func (m *DeviceLock) String() string            { return proto.CompactTextString(m) }
func (*DeviceLock) ProtoMessage()               {}
func (*DeviceLock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *DeviceLock) GetPin() string {
	if m != nil {
		return m.Pin
	}
	return ""
}

func (m *DeviceLock) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DeviceLock) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type Settings struct {
	Settings []*Setting `protobuf:"bytes,1,rep,name=settings" json:"settings,omitempty"`
}

func (m *Settings) Reset()                    { *m = Settings{} }
func (m *Settings) String() string            { return proto.CompactTextString(m) }
func (*Settings) ProtoMessage()               {}
func (*Settings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Settings) GetSettings() []*Setting {
	if m != nil {
		return m.Settings
	}
	return nil
}

type Setting struct {
	Item       string             `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
	DeviceName *DeviceNameSetting `protobuf:"bytes,2,opt,name=device_name,json=deviceName" json:"device_name,omitempty"`
	Hostname   *HostnameSetting   `protobuf:"bytes,3,opt,name=hostname" json:"hostname,omitempty"`
}

func (m *Setting) Reset()                    { *m = Setting{} }
func (m *Setting) String() string            { return proto.CompactTextString(m) }
func (*Setting) ProtoMessage()               {}
func (*Setting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *Setting) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *Setting) GetDeviceName() *DeviceNameSetting {
	if m != nil {
		return m.DeviceName
	}
	return nil
}

func (m *Setting) GetHostname() *HostnameSetting {
	if m != nil {
		return m.Hostname
	}
	return nil
}

type DeviceNameSetting struct {
	DeviceName string `protobuf:"bytes,1,opt,name=device_name,json=deviceName" json:"device_name,omitempty"`
}

func (m *DeviceNameSetting) Reset()                    { *m = DeviceNameSetting{} }
func (m *DeviceNameSetting) String() string            { return proto.CompactTextString(m) }
func (*DeviceNameSetting) ProtoMessage()               {}
func (*DeviceNameSetting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *DeviceNameSetting) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

type HostnameSetting struct {
	Hostname string `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
}

func (m *HostnameSetting) Reset()                    { *m = HostnameSetting{} }
func (m *HostnameSetting) String() string            { return proto.CompactTextString(m) }
func (*HostnameSetting) ProtoMessage()               {}
func (*HostnameSetting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *HostnameSetting) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "commandproto.Event")
	proto.RegisterType((*Payload)(nil), "commandproto.Payload")
	proto.RegisterType((*Command)(nil), "commandproto.Command")
	proto.RegisterType((*ScheduleOSUpdate)(nil), "commandproto.ScheduleOSUpdate")
	proto.RegisterType((*OSUpdate)(nil), "commandproto.OSUpdate")
	proto.RegisterType((*ScheduleOSUpdateScan)(nil), "commandproto.ScheduleOSUpdateScan")
	proto.RegisterType((*AccountConfiguration)(nil), "commandproto.AccountConfiguration")
	proto.RegisterType((*AutoSetupAdminAccounts)(nil), "commandproto.AutoSetupAdminAccounts")
	proto.RegisterType((*DeviceInformation)(nil), "commandproto.DeviceInformation")
	proto.RegisterType((*InstallProfile)(nil), "commandproto.InstallProfile")
	proto.RegisterType((*RemoveProfile)(nil), "commandproto.RemoveProfile")
	proto.RegisterType((*DeleteUser)(nil), "commandproto.DeleteUser")
	proto.RegisterType((*InstallApplication)(nil), "commandproto.InstallApplication")
	proto.RegisterType((*EraseDevice)(nil), "commandproto.EraseDevice")
	proto.RegisterType((*DeviceLock)(nil), "commandproto.DeviceLock")
	proto.RegisterType((*Settings)(nil), "commandproto.Settings")
	proto.RegisterType((*Setting)(nil), "commandproto.Setting")
	proto.RegisterType((*DeviceNameSetting)(nil), "commandproto.DeviceNameSetting")
	proto.RegisterType((*HostnameSetting)(nil), "commandproto.HostnameSetting")
}

func init() { proto.RegisterFile("command.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x56, 0x5d, 0x6f, 0x1c, 0x35,
	0x17, 0xd6, 0xee, 0x36, 0xd9, 0xdd, 0xb3, 0xd9, 0x24, 0xf5, 0x9b, 0xa4, 0xd3, 0xb7, 0xb4, 0x09,
	0x53, 0x40, 0x29, 0xea, 0x07, 0x14, 0x84, 0x54, 0x09, 0x24, 0xd2, 0xa6, 0xa8, 0x15, 0xfd, 0x08,
	0x0e, 0x01, 0x21, 0x84, 0x2c, 0x67, 0xc6, 0xbb, 0x6b, 0x65, 0xc6, 0x9e, 0xda, 0x9e, 0xa0, 0xbd,
	0xe6, 0x17, 0x70, 0x8b, 0xc4, 0x0d, 0xbf, 0x85, 0x1f, 0x86, 0xfc, 0x35, 0xfb, 0x91, 0xed, 0xdd,
	0x9c, 0xc7, 0x8f, 0x9f, 0x39, 0xe3, 0x73, 0x9e, 0xe3, 0x81, 0x61, 0x26, 0xcb, 0x92, 0x8a, 0xfc,
	0x61, 0xa5, 0xa4, 0x91, 0x68, 0x23, 0x84, 0x2e, 0x4a, 0xff, 0x69, 0xc1, 0xda, 0xf3, 0x4b, 0x26,
	0x0c, 0xda, 0x84, 0x36, 0xcf, 0x93, 0xd6, 0x41, 0xeb, 0xb0, 0x8f, 0xdb, 0x3c, 0x47, 0x08, 0xae,
	0x19, 0x5e, 0xb2, 0xa4, 0x7d, 0xd0, 0x3a, 0xec, 0x60, 0xf7, 0x8c, 0x1e, 0x41, 0xb7, 0xa2, 0xd3,
	0x42, 0xd2, 0x3c, 0xe9, 0x1c, 0xb4, 0x0e, 0x07, 0x8f, 0x77, 0x1f, 0xce, 0xab, 0x3d, 0x3c, 0xf1,
	0x8b, 0x38, 0xb2, 0xd0, 0x3e, 0x0c, 0x72, 0x76, 0xc9, 0x33, 0x46, 0xea, 0x9c, 0xe7, 0xc9, 0x35,
	0xa7, 0x0e, 0x1e, 0x3a, 0xcb, 0x79, 0x8e, 0xee, 0xc2, 0x30, 0x70, 0xc9, 0xf9, 0xd4, 0x30, 0x9d,
	0xac, 0x1d, 0xb4, 0x0e, 0x37, 0xf0, 0x46, 0x00, 0x9f, 0x5a, 0x2c, 0xfd, 0x0d, 0xba, 0x41, 0x19,
	0x7d, 0x08, 0x31, 0x7f, 0x52, 0xd7, 0x4d, 0xbe, 0x83, 0x80, 0x9d, 0xd5, 0x3c, 0xb7, 0x49, 0x86,
	0xd0, 0xe5, 0x7e, 0x25, 0xc9, 0x67, 0x3e, 0xc0, 0x91, 0x95, 0xfe, 0xbb, 0x0e, 0xdd, 0x00, 0x5a,
	0x7d, 0xc5, 0xde, 0xd5, 0x4c, 0x1b, 0x62, 0xa6, 0x15, 0x8b, 0xfa, 0x01, 0xfb, 0x71, 0x5a, 0x31,
	0xf4, 0x06, 0x50, 0xf8, 0x26, 0x2e, 0x46, 0x52, 0x95, 0xd4, 0x70, 0x29, 0xc2, 0xab, 0xf6, 0x17,
	0x5f, 0x75, 0xec, 0x78, 0x2f, 0x67, 0x34, 0x7c, 0x3d, 0x5f, 0x86, 0xd0, 0x73, 0xd8, 0xe2, 0x42,
	0x1b, 0x5a, 0x14, 0xa4, 0x52, 0x72, 0xc4, 0x0b, 0x16, 0x0e, 0xf7, 0x83, 0x45, 0xb1, 0x97, 0x9e,
	0x74, 0xe2, 0x39, 0x78, 0x93, 0x2f, 0xc4, 0xe8, 0x07, 0xf8, 0x5f, 0x94, 0xa1, 0x55, 0x55, 0xf0,
	0xcc, 0xe7, 0x75, 0xcd, 0x49, 0x1d, 0xac, 0x94, 0x3a, 0x9a, 0xf1, 0x30, 0xe2, 0x57, 0x30, 0xf4,
	0x33, 0xec, 0xd2, 0x2c, 0x93, 0xb5, 0x30, 0x24, 0x93, 0x62, 0xc4, 0xc7, 0xb5, 0xf2, 0xa2, 0x6b,
	0x4e, 0x34, 0x5d, 0x14, 0x3d, 0xf2, 0xd4, 0x67, 0xf3, 0x4c, 0xbc, 0x43, 0x57, 0xa0, 0xe8, 0x15,
	0x20, 0x9d, 0x4d, 0x58, 0x5e, 0x17, 0x8c, 0x48, 0x4d, 0xea, 0x2a, 0xa7, 0x86, 0x25, 0xeb, 0x4e,
	0xf5, 0xce, 0xa2, 0xea, 0x69, 0xe0, 0xbd, 0x3d, 0x3d, 0x73, 0x2c, 0xbc, 0x1d, 0x77, 0xbe, 0xd5,
	0x1e, 0x41, 0xbf, 0xc0, 0x8d, 0xab, 0x6a, 0x44, 0x67, 0x54, 0x24, 0xdd, 0x55, 0x89, 0x2e, 0x4b,
	0x9e, 0x66, 0x54, 0xe0, 0x9d, 0x65, 0x59, 0x8b, 0xa2, 0xa7, 0xb0, 0xa9, 0x58, 0x29, 0x2f, 0x59,
	0x53, 0x9a, 0x9e, 0x53, 0xbc, 0xb5, 0xa8, 0x88, 0x1d, 0x27, 0x56, 0x66, 0xa8, 0xe6, 0x43, 0xf4,
	0xc4, 0x7a, 0xa0, 0x60, 0x86, 0x91, 0x5a, 0x33, 0x95, 0xf4, 0x9d, 0x40, 0xb2, 0xdc, 0x28, 0x96,
	0x70, 0xa6, 0x99, 0xb2, 0xee, 0x88, 0xcf, 0xe8, 0x31, 0xf4, 0x34, 0x33, 0x86, 0x8b, 0xb1, 0x4e,
	0xc0, 0xed, 0xdb, 0x5b, 0xfa, 0x94, 0xb0, 0x8a, 0x1b, 0x1e, 0xfa, 0x1a, 0x36, 0x98, 0xa2, 0x9a,
	0x11, 0xdf, 0x69, 0xc9, 0xc0, 0xed, 0xbb, 0xb9, 0xb8, 0xef, 0xb9, 0x65, 0xf8, 0xee, 0xc4, 0x03,
	0x36, 0x0b, 0x7c, 0xb2, 0xae, 0xb9, 0x0b, 0x99, 0x5d, 0x24, 0x1b, 0xab, 0x93, 0xb5, 0x84, 0x57,
	0x32, 0xbb, 0x88, 0x56, 0xb6, 0xcf, 0xe9, 0x31, 0x6c, 0x2f, 0x9f, 0x2c, 0xfa, 0x0c, 0xba, 0xbe,
	0x1c, 0x3a, 0x69, 0x1d, 0x74, 0xae, 0xe6, 0xdf, 0x54, 0x35, 0xd2, 0x52, 0x0c, 0xbd, 0x66, 0xf7,
	0x3e, 0x0c, 0x2a, 0x25, 0xf3, 0x3a, 0x33, 0xe4, 0x82, 0x4d, 0x83, 0x17, 0x21, 0x40, 0xdf, 0xb3,
	0x29, 0xfa, 0x18, 0x36, 0x9b, 0x9e, 0xcf, 0x1a, 0x1b, 0xf6, 0xf1, 0x30, 0x36, 0xb3, 0x03, 0xd3,
	0xfb, 0xb0, 0xb3, 0xaa, 0xe6, 0x68, 0x07, 0xd6, 0x46, 0x52, 0x65, 0xde, 0xe5, 0x3d, 0xec, 0x83,
	0xf4, 0xef, 0x36, 0xec, 0x1c, 0xad, 0xee, 0xda, 0xbb, 0xfa, 0x82, 0x57, 0xa4, 0x52, 0xbc, 0xa4,
	0x6a, 0x4a, 0x34, 0x33, 0x75, 0x45, 0x1a, 0x87, 0x28, 0xe6, 0xcd, 0xe1, 0xc5, 0xf6, 0x2d, 0xf5,
	0xc4, 0x33, 0x4f, 0x2d, 0x31, 0x4a, 0x06, 0x1a, 0xfa, 0x09, 0xee, 0x69, 0x66, 0xde, 0x23, 0x46,
	0x35, 0x51, 0x6c, 0x5c, 0x17, 0x54, 0xf9, 0xa6, 0x69, 0x3b, 0xcd, 0xbb, 0x9a, 0x99, 0x15, 0x92,
	0x47, 0x1a, 0x7b, 0xae, 0xeb, 0x19, 0x02, 0x37, 0x69, 0x6d, 0x64, 0x14, 0xcc, 0x4b, 0x2e, 0xa2,
	0xac, 0x4e, 0x3a, 0xae, 0x08, 0x1f, 0x2d, 0x19, 0xb7, 0x36, 0xd2, 0xeb, 0x59, 0x72, 0x10, 0xd5,
	0x78, 0x8f, 0xae, 0xc4, 0xd3, 0x3f, 0x5b, 0xb0, 0xb7, 0x7a, 0x0b, 0xba, 0x0d, 0xa0, 0x27, 0x52,
	0x19, 0x22, 0x68, 0x19, 0x67, 0x67, 0xdf, 0x21, 0x6f, 0x68, 0xc9, 0xd0, 0x2d, 0xe8, 0x8f, 0xea,
	0xa2, 0xf0, 0xab, 0xbe, 0x52, 0x3d, 0x0b, 0xb8, 0x45, 0x77, 0x13, 0x68, 0xfd, 0xbb, 0x54, 0x39,
	0x99, 0x50, 0x3d, 0x71, 0x43, 0xd0, 0xdd, 0x04, 0x1e, 0x7c, 0x41, 0xf5, 0x04, 0xed, 0xc1, 0xfa,
	0x84, 0xe7, 0x39, 0xf3, 0x73, 0xad, 0x87, 0x43, 0x94, 0x3e, 0x80, 0xeb, 0x57, 0x66, 0x2d, 0x4a,
	0xa0, 0xfb, 0xae, 0x66, 0x8a, 0x87, 0xe6, 0xeb, 0xe3, 0x18, 0xa6, 0x9f, 0xc2, 0xe6, 0xe2, 0x34,
	0xb5, 0xdc, 0x78, 0xb3, 0xb5, 0xdc, 0x7b, 0x63, 0x98, 0x3e, 0x82, 0xe1, 0x82, 0xbd, 0xd1, 0x1d,
	0x00, 0x9e, 0x33, 0x61, 0xf8, 0x88, 0x33, 0x15, 0x9b, 0x72, 0x86, 0xa4, 0x6f, 0x01, 0x66, 0x76,
	0x46, 0xff, 0x87, 0x9e, 0xad, 0xe0, 0xdc, 0x81, 0x34, 0xb1, 0x6d, 0x5f, 0xd7, 0x72, 0xc4, 0x59,
	0x3e, 0xb6, 0x6f, 0x0f, 0x0f, 0x1d, 0x7a, 0x1c, 0xc0, 0xf4, 0x8f, 0x36, 0xa0, 0xab, 0x13, 0x1b,
	0x7d, 0x02, 0x5b, 0xdc, 0xd4, 0x82, 0x69, 0xa2, 0x8d, 0x54, 0x8c, 0x84, 0xdb, 0xb0, 0x83, 0x87,
	0x1e, 0x3e, 0xb5, 0xe8, 0xcb, 0x7c, 0x29, 0xdf, 0xf6, 0x72, 0xbe, 0xf6, 0xca, 0x2b, 0xa9, 0xe0,
	0x23, 0x7b, 0xe7, 0xd5, 0xaa, 0x70, 0xe7, 0xde, 0xc7, 0x83, 0x88, 0x9d, 0xa9, 0x02, 0xdd, 0x83,
	0xed, 0x92, 0x0a, 0x3a, 0x66, 0x25, 0x13, 0x86, 0x8c, 0x0a, 0x3a, 0xd6, 0xae, 0x00, 0x1d, 0xbc,
	0x35, 0xc3, 0xbf, 0xb3, 0xb0, 0xf5, 0xac, 0x90, 0x86, 0x78, 0x38, 0x77, 0x37, 0x45, 0x0f, 0x83,
	0x90, 0xe6, 0xb5, 0x47, 0xd0, 0x57, 0x70, 0x23, 0x9b, 0x50, 0x31, 0x66, 0x64, 0x4e, 0x52, 0x9b,
	0x78, 0x01, 0xf4, 0xf1, 0xae, 0x5f, 0x7e, 0xdd, 0xac, 0x9e, 0xda, 0xc5, 0xf4, 0x35, 0x0c, 0xe6,
	0xa6, 0x16, 0xda, 0x86, 0x4e, 0xc5, 0x45, 0x38, 0x52, 0xfb, 0x88, 0xee, 0x03, 0xaa, 0x14, 0xd3,
	0x4c, 0x5d, 0x32, 0x92, 0x53, 0x43, 0x49, 0x55, 0xd0, 0x78, 0xa2, 0xdb, 0x71, 0xe5, 0x98, 0x1a,
	0x7a, 0x52, 0x50, 0x91, 0xfe, 0x6a, 0xab, 0x14, 0x67, 0xd7, 0x0a, 0xb5, 0x04, 0xba, 0x25, 0xd3,
	0x9a, 0x8e, 0x63, 0xa7, 0xc6, 0xd0, 0x9e, 0x57, 0x35, 0x91, 0x82, 0x11, 0x51, 0x97, 0xe7, 0x4c,
	0xc5, 0xf3, 0x72, 0xd8, 0x1b, 0x07, 0xa5, 0xdf, 0x40, 0x2f, 0x4e, 0x66, 0xf4, 0xf9, 0xdc, 0x0c,
	0xf7, 0x33, 0x70, 0x77, 0xe5, 0x0c, 0x9f, 0x8d, 0xf0, 0xf4, 0xaf, 0x16, 0x74, 0x03, 0x6a, 0x7f,
	0xc3, 0xb8, 0x61, 0x65, 0x48, 0xcd, 0x3d, 0xa3, 0x6f, 0x9b, 0x21, 0xdd, 0x38, 0xe9, 0x3d, 0xbf,
	0x1e, 0xd6, 0x59, 0x51, 0x3f, 0xcc, 0x6a, 0x67, 0xb6, 0x27, 0xd0, 0x9b, 0x48, 0x6d, 0xdc, 0x76,
	0xff, 0xb3, 0x71, 0x7b, 0x71, 0xfb, 0x8b, 0xb0, 0xda, 0x24, 0x17, 0xe9, 0xe9, 0x97, 0xd1, 0x6a,
	0x73, 0xda, 0x73, 0xff, 0x79, 0x73, 0x8d, 0x3e, 0xf7, 0xc2, 0xf4, 0x01, 0x6c, 0x2d, 0x49, 0x5a,
	0x67, 0x34, 0x39, 0x04, 0x67, 0xc4, 0xf8, 0x7c, 0xdd, 0x65, 0xf1, 0xc5, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x86, 0xfe, 0x3d, 0xe0, 0xbc, 0x0a, 0x00, 0x00,
}
