// Code generated by protoc-gen-go.
// source: command.proto
// DO NOT EDIT!

/*
Package commandproto is a generated protocol buffer package.

It is generated from these files:
	command.proto

It has these top-level messages:
	Event
	Payload
	Command
	DeviceInformation
	InstallProfile
	InstallApplication
*/
package commandproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Id         string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Time       int64    `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Payload    *Payload `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	DeviceUdid string   `protobuf:"bytes,4,opt,name=device_udid,json=deviceUdid" json:"device_udid,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Event) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Event) GetDeviceUdid() string {
	if m != nil {
		return m.DeviceUdid
	}
	return ""
}

type Payload struct {
	CommandUuid string   `protobuf:"bytes,1,opt,name=command_uuid,json=commandUuid" json:"command_uuid,omitempty"`
	Command     *Command `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
}

func (m *Payload) Reset()                    { *m = Payload{} }
func (m *Payload) String() string            { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()               {}
func (*Payload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Payload) GetCommandUuid() string {
	if m != nil {
		return m.CommandUuid
	}
	return ""
}

func (m *Payload) GetCommand() *Command {
	if m != nil {
		return m.Command
	}
	return nil
}

type Command struct {
	RequestType        string              `protobuf:"bytes,1,opt,name=request_type,json=requestType" json:"request_type,omitempty"`
	DeviceInformation  *DeviceInformation  `protobuf:"bytes,2,opt,name=device_information,json=deviceInformation" json:"device_information,omitempty"`
	InstallProfile     *InstallProfile     `protobuf:"bytes,3,opt,name=install_profile,json=installProfile" json:"install_profile,omitempty"`
	InstallApplication *InstallApplication `protobuf:"bytes,4,opt,name=install_application,json=installApplication" json:"install_application,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Command) GetRequestType() string {
	if m != nil {
		return m.RequestType
	}
	return ""
}

func (m *Command) GetDeviceInformation() *DeviceInformation {
	if m != nil {
		return m.DeviceInformation
	}
	return nil
}

func (m *Command) GetInstallProfile() *InstallProfile {
	if m != nil {
		return m.InstallProfile
	}
	return nil
}

func (m *Command) GetInstallApplication() *InstallApplication {
	if m != nil {
		return m.InstallApplication
	}
	return nil
}

type DeviceInformation struct {
	Queries []string `protobuf:"bytes,1,rep,name=queries" json:"queries,omitempty"`
}

func (m *DeviceInformation) Reset()                    { *m = DeviceInformation{} }
func (m *DeviceInformation) String() string            { return proto.CompactTextString(m) }
func (*DeviceInformation) ProtoMessage()               {}
func (*DeviceInformation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeviceInformation) GetQueries() []string {
	if m != nil {
		return m.Queries
	}
	return nil
}

type InstallProfile struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *InstallProfile) Reset()                    { *m = InstallProfile{} }
func (m *InstallProfile) String() string            { return proto.CompactTextString(m) }
func (*InstallProfile) ProtoMessage()               {}
func (*InstallProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *InstallProfile) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type InstallApplication struct {
	ItunesStoreId         int64  `protobuf:"varint,1,opt,name=itunes_store_id,json=itunesStoreId" json:"itunes_store_id,omitempty"`
	Identifier            string `protobuf:"bytes,2,opt,name=identifier" json:"identifier,omitempty"`
	ManifestUrl           string `protobuf:"bytes,3,opt,name=manifest_url,json=manifestUrl" json:"manifest_url,omitempty"`
	ManagementFlags       int64  `protobuf:"varint,4,opt,name=management_flags,json=managementFlags" json:"management_flags,omitempty"`
	NotManaged            bool   `protobuf:"varint,5,opt,name=not_managed,json=notManaged" json:"not_managed,omitempty"`
	ChangeManagementState string `protobuf:"bytes,6,opt,name=change_management_state,json=changeManagementState" json:"change_management_state,omitempty"`
}

func (m *InstallApplication) Reset()                    { *m = InstallApplication{} }
func (m *InstallApplication) String() string            { return proto.CompactTextString(m) }
func (*InstallApplication) ProtoMessage()               {}
func (*InstallApplication) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *InstallApplication) GetItunesStoreId() int64 {
	if m != nil {
		return m.ItunesStoreId
	}
	return 0
}

func (m *InstallApplication) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *InstallApplication) GetManifestUrl() string {
	if m != nil {
		return m.ManifestUrl
	}
	return ""
}

func (m *InstallApplication) GetManagementFlags() int64 {
	if m != nil {
		return m.ManagementFlags
	}
	return 0
}

func (m *InstallApplication) GetNotManaged() bool {
	if m != nil {
		return m.NotManaged
	}
	return false
}

func (m *InstallApplication) GetChangeManagementState() string {
	if m != nil {
		return m.ChangeManagementState
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "commandproto.Event")
	proto.RegisterType((*Payload)(nil), "commandproto.Payload")
	proto.RegisterType((*Command)(nil), "commandproto.Command")
	proto.RegisterType((*DeviceInformation)(nil), "commandproto.DeviceInformation")
	proto.RegisterType((*InstallProfile)(nil), "commandproto.InstallProfile")
	proto.RegisterType((*InstallApplication)(nil), "commandproto.InstallApplication")
}

func init() { proto.RegisterFile("command.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x65, 0x3b, 0x6d, 0xc8, 0xa4, 0x4d, 0xe8, 0xa2, 0x0a, 0x1f, 0x10, 0x35, 0x3e, 0x20,
	0x83, 0x44, 0x90, 0x40, 0xe2, 0x8e, 0xa0, 0x48, 0x39, 0x14, 0x95, 0x2d, 0x39, 0x22, 0x6b, 0xc9,
	0xae, 0xc3, 0x48, 0xf6, 0xae, 0x6b, 0xaf, 0x23, 0xe5, 0xc0, 0x89, 0xef, 0xc0, 0xe7, 0x45, 0xfb,
	0xc7, 0xf9, 0x43, 0x7a, 0xcb, 0xfc, 0xe6, 0xe5, 0xcd, 0xf3, 0xcc, 0xc2, 0xf9, 0x52, 0x55, 0x15,
	0x93, 0x7c, 0x56, 0x37, 0x4a, 0x2b, 0x72, 0xe6, 0x4b, 0x5b, 0xa5, 0xbf, 0xe1, 0xe4, 0x7a, 0x2d,
	0xa4, 0x26, 0x13, 0x08, 0x91, 0xc7, 0x41, 0x12, 0x64, 0x23, 0x1a, 0x22, 0x27, 0x04, 0x06, 0x1a,
	0x2b, 0x11, 0x87, 0x49, 0x90, 0x45, 0xd4, 0xfe, 0x26, 0x6f, 0x61, 0x58, 0xb3, 0x4d, 0xa9, 0x18,
	0x8f, 0xa3, 0x24, 0xc8, 0xc6, 0xef, 0x2e, 0x67, 0xfb, 0x66, 0xb3, 0x5b, 0xd7, 0xa4, 0xbd, 0x8a,
	0x5c, 0xc1, 0x98, 0x8b, 0x35, 0x2e, 0x45, 0xde, 0x71, 0xe4, 0xf1, 0xc0, 0xba, 0x83, 0x43, 0x0b,
	0x8e, 0x3c, 0xfd, 0x01, 0x43, 0xff, 0x27, 0xf2, 0x02, 0xfa, 0x64, 0x79, 0xd7, 0x6d, 0xa3, 0x8c,
	0x3d, 0x5b, 0x74, 0xc8, 0xcd, 0x7c, 0x5f, 0xda, 0x58, 0x47, 0xf3, 0x3f, 0xb9, 0x82, 0xf6, 0xaa,
	0xf4, 0x6f, 0x08, 0x43, 0x0f, 0x8d, 0x7f, 0x23, 0xee, 0x3b, 0xd1, 0xea, 0x5c, 0x6f, 0x6a, 0xd1,
	0xfb, 0x7b, 0xf6, 0x7d, 0x53, 0x0b, 0xf2, 0x15, 0x88, 0x8f, 0x8b, 0xb2, 0x50, 0x4d, 0xc5, 0x34,
	0x2a, 0xe9, 0x47, 0x5d, 0x1d, 0x8e, 0xfa, 0x6c, 0x75, 0xf3, 0x9d, 0x8c, 0x5e, 0xf0, 0xff, 0x11,
	0xb9, 0x86, 0x29, 0xca, 0x56, 0xb3, 0xb2, 0xcc, 0xeb, 0x46, 0x15, 0x58, 0x0a, 0xbf, 0xb7, 0x67,
	0x87, 0x66, 0x73, 0x27, 0xba, 0x75, 0x1a, 0x3a, 0xc1, 0x83, 0x9a, 0x7c, 0x83, 0x27, 0xbd, 0x0d,
	0xab, 0xeb, 0x12, 0x97, 0x2e, 0xd7, 0xc0, 0x5a, 0x25, 0x0f, 0x5a, 0x7d, 0xdc, 0xe9, 0x28, 0xc1,
	0x23, 0x96, 0xbe, 0x81, 0x8b, 0xa3, 0x2f, 0x20, 0x31, 0x0c, 0xef, 0x3b, 0xd1, 0xa0, 0x68, 0xe3,
	0x20, 0x89, 0xb2, 0x11, 0xed, 0xcb, 0xf4, 0x35, 0x4c, 0x0e, 0x33, 0x1a, 0x6d, 0xff, 0x14, 0xcc,
	0x22, 0xcf, 0xb6, 0x37, 0x4f, 0xff, 0x84, 0x40, 0x8e, 0x53, 0x90, 0x97, 0x30, 0x45, 0xdd, 0x49,
	0xd1, 0xe6, 0xad, 0x56, 0x8d, 0xc8, 0xfd, 0x85, 0x23, 0x7a, 0xee, 0xf0, 0x9d, 0xa1, 0x73, 0x4e,
	0x9e, 0x03, 0x20, 0x17, 0x52, 0x63, 0x81, 0xa2, 0xb1, 0xbb, 0x1f, 0xd1, 0x3d, 0x62, 0xce, 0x58,
	0x31, 0x89, 0x85, 0xb9, 0x63, 0xd7, 0x94, 0x76, 0xa1, 0x23, 0x3a, 0xee, 0xd9, 0xa2, 0x29, 0xc9,
	0x2b, 0x78, 0x5c, 0x31, 0xc9, 0x56, 0xa2, 0x12, 0x52, 0xe7, 0x45, 0xc9, 0x56, 0xad, 0x5d, 0x56,
	0x44, 0xa7, 0x3b, 0xfe, 0xc5, 0x60, 0xf3, 0x40, 0xa5, 0xd2, 0xb9, 0xc3, 0x3c, 0x3e, 0x49, 0x82,
	0xec, 0x11, 0x05, 0xa9, 0xf4, 0x8d, 0x23, 0xe4, 0x03, 0x3c, 0x5d, 0xfe, 0x62, 0x72, 0x25, 0xf2,
	0x3d, 0xcb, 0x56, 0x33, 0x2d, 0xe2, 0x53, 0x3b, 0xf9, 0xd2, 0xb5, 0x6f, 0xb6, 0xdd, 0x3b, 0xd3,
	0xfc, 0x79, 0x6a, 0xcf, 0xf1, 0xfe, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xe7, 0xa3, 0x8e,
	0x7d, 0x03, 0x00, 0x00,
}
