// Code generated by protoc-gen-go.
// source: command.proto
// DO NOT EDIT!

/*
Package commandproto is a generated protocol buffer package.

It is generated from these files:
	command.proto

It has these top-level messages:
	Event
	Payload
	Command
	ScheduleOSUpdate
	OSUpdate
	ScheduleOSUpdateScan
	AccountConfiguration
	AutoSetupAdminAccounts
	DeviceInformation
	InstallProfile
	InstallApplication
*/
package commandproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Id         string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Time       int64    `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Payload    *Payload `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	DeviceUdid string   `protobuf:"bytes,4,opt,name=device_udid,json=deviceUdid" json:"device_udid,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Event) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Event) GetDeviceUdid() string {
	if m != nil {
		return m.DeviceUdid
	}
	return ""
}

type Payload struct {
	CommandUuid string   `protobuf:"bytes,1,opt,name=command_uuid,json=commandUuid" json:"command_uuid,omitempty"`
	Command     *Command `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
}

func (m *Payload) Reset()                    { *m = Payload{} }
func (m *Payload) String() string            { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()               {}
func (*Payload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Payload) GetCommandUuid() string {
	if m != nil {
		return m.CommandUuid
	}
	return ""
}

func (m *Payload) GetCommand() *Command {
	if m != nil {
		return m.Command
	}
	return nil
}

type Command struct {
	RequestType          string                `protobuf:"bytes,1,opt,name=request_type,json=requestType" json:"request_type,omitempty"`
	DeviceInformation    *DeviceInformation    `protobuf:"bytes,2,opt,name=device_information,json=deviceInformation" json:"device_information,omitempty"`
	InstallProfile       *InstallProfile       `protobuf:"bytes,3,opt,name=install_profile,json=installProfile" json:"install_profile,omitempty"`
	InstallApplication   *InstallApplication   `protobuf:"bytes,4,opt,name=install_application,json=installApplication" json:"install_application,omitempty"`
	AccountConfiguration *AccountConfiguration `protobuf:"bytes,5,opt,name=account_configuration,json=accountConfiguration" json:"account_configuration,omitempty"`
	ScheduleOsUpdate     *ScheduleOSUpdate     `protobuf:"bytes,6,opt,name=schedule_os_update,json=scheduleOsUpdate" json:"schedule_os_update,omitempty"`
	ScheduleOsUpdateScan *ScheduleOSUpdateScan `protobuf:"bytes,7,opt,name=schedule_os_update_scan,json=scheduleOsUpdateScan" json:"schedule_os_update_scan,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Command) GetRequestType() string {
	if m != nil {
		return m.RequestType
	}
	return ""
}

func (m *Command) GetDeviceInformation() *DeviceInformation {
	if m != nil {
		return m.DeviceInformation
	}
	return nil
}

func (m *Command) GetInstallProfile() *InstallProfile {
	if m != nil {
		return m.InstallProfile
	}
	return nil
}

func (m *Command) GetInstallApplication() *InstallApplication {
	if m != nil {
		return m.InstallApplication
	}
	return nil
}

func (m *Command) GetAccountConfiguration() *AccountConfiguration {
	if m != nil {
		return m.AccountConfiguration
	}
	return nil
}

func (m *Command) GetScheduleOsUpdate() *ScheduleOSUpdate {
	if m != nil {
		return m.ScheduleOsUpdate
	}
	return nil
}

func (m *Command) GetScheduleOsUpdateScan() *ScheduleOSUpdateScan {
	if m != nil {
		return m.ScheduleOsUpdateScan
	}
	return nil
}

type ScheduleOSUpdate struct {
	Updates []*OSUpdate `protobuf:"bytes,1,rep,name=updates" json:"updates,omitempty"`
}

func (m *ScheduleOSUpdate) Reset()                    { *m = ScheduleOSUpdate{} }
func (m *ScheduleOSUpdate) String() string            { return proto.CompactTextString(m) }
func (*ScheduleOSUpdate) ProtoMessage()               {}
func (*ScheduleOSUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ScheduleOSUpdate) GetUpdates() []*OSUpdate {
	if m != nil {
		return m.Updates
	}
	return nil
}

type OSUpdate struct {
	ProductKey    string `protobuf:"bytes,1,opt,name=product_key,json=productKey" json:"product_key,omitempty"`
	InstallAction string `protobuf:"bytes,2,opt,name=install_action,json=installAction" json:"install_action,omitempty"`
}

func (m *OSUpdate) Reset()                    { *m = OSUpdate{} }
func (m *OSUpdate) String() string            { return proto.CompactTextString(m) }
func (*OSUpdate) ProtoMessage()               {}
func (*OSUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *OSUpdate) GetProductKey() string {
	if m != nil {
		return m.ProductKey
	}
	return ""
}

func (m *OSUpdate) GetInstallAction() string {
	if m != nil {
		return m.InstallAction
	}
	return ""
}

type ScheduleOSUpdateScan struct {
	Force bool `protobuf:"varint,1,opt,name=force" json:"force,omitempty"`
}

func (m *ScheduleOSUpdateScan) Reset()                    { *m = ScheduleOSUpdateScan{} }
func (m *ScheduleOSUpdateScan) String() string            { return proto.CompactTextString(m) }
func (*ScheduleOSUpdateScan) ProtoMessage()               {}
func (*ScheduleOSUpdateScan) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ScheduleOSUpdateScan) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type AccountConfiguration struct {
	SkipPrimarySetupAccountCreation     bool                      `protobuf:"varint,1,opt,name=skip_primary_setup_account_creation,json=skipPrimarySetupAccountCreation" json:"skip_primary_setup_account_creation,omitempty"`
	SetPrimarySetupAccountAsRegularUser bool                      `protobuf:"varint,2,opt,name=set_primary_setup_account_as_regular_user,json=setPrimarySetupAccountAsRegularUser" json:"set_primary_setup_account_as_regular_user,omitempty"`
	AutoSetupAdminAccounts              []*AutoSetupAdminAccounts `protobuf:"bytes,3,rep,name=auto_setup_admin_accounts,json=autoSetupAdminAccounts" json:"auto_setup_admin_accounts,omitempty"`
}

func (m *AccountConfiguration) Reset()                    { *m = AccountConfiguration{} }
func (m *AccountConfiguration) String() string            { return proto.CompactTextString(m) }
func (*AccountConfiguration) ProtoMessage()               {}
func (*AccountConfiguration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AccountConfiguration) GetSkipPrimarySetupAccountCreation() bool {
	if m != nil {
		return m.SkipPrimarySetupAccountCreation
	}
	return false
}

func (m *AccountConfiguration) GetSetPrimarySetupAccountAsRegularUser() bool {
	if m != nil {
		return m.SetPrimarySetupAccountAsRegularUser
	}
	return false
}

func (m *AccountConfiguration) GetAutoSetupAdminAccounts() []*AutoSetupAdminAccounts {
	if m != nil {
		return m.AutoSetupAdminAccounts
	}
	return nil
}

type AutoSetupAdminAccounts struct {
	ShortName    string `protobuf:"bytes,1,opt,name=short_name,json=shortName" json:"short_name,omitempty"`
	FullName     string `protobuf:"bytes,2,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	PasswordHash []byte `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Hidden       bool   `protobuf:"varint,4,opt,name=hidden" json:"hidden,omitempty"`
}

func (m *AutoSetupAdminAccounts) Reset()                    { *m = AutoSetupAdminAccounts{} }
func (m *AutoSetupAdminAccounts) String() string            { return proto.CompactTextString(m) }
func (*AutoSetupAdminAccounts) ProtoMessage()               {}
func (*AutoSetupAdminAccounts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *AutoSetupAdminAccounts) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *AutoSetupAdminAccounts) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *AutoSetupAdminAccounts) GetPasswordHash() []byte {
	if m != nil {
		return m.PasswordHash
	}
	return nil
}

func (m *AutoSetupAdminAccounts) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

type DeviceInformation struct {
	Queries []string `protobuf:"bytes,1,rep,name=queries" json:"queries,omitempty"`
}

func (m *DeviceInformation) Reset()                    { *m = DeviceInformation{} }
func (m *DeviceInformation) String() string            { return proto.CompactTextString(m) }
func (*DeviceInformation) ProtoMessage()               {}
func (*DeviceInformation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeviceInformation) GetQueries() []string {
	if m != nil {
		return m.Queries
	}
	return nil
}

type InstallProfile struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *InstallProfile) Reset()                    { *m = InstallProfile{} }
func (m *InstallProfile) String() string            { return proto.CompactTextString(m) }
func (*InstallProfile) ProtoMessage()               {}
func (*InstallProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *InstallProfile) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type InstallApplication struct {
	ItunesStoreId         int64  `protobuf:"varint,1,opt,name=itunes_store_id,json=itunesStoreId" json:"itunes_store_id,omitempty"`
	Identifier            string `protobuf:"bytes,2,opt,name=identifier" json:"identifier,omitempty"`
	ManifestUrl           string `protobuf:"bytes,3,opt,name=manifest_url,json=manifestUrl" json:"manifest_url,omitempty"`
	ManagementFlags       int64  `protobuf:"varint,4,opt,name=management_flags,json=managementFlags" json:"management_flags,omitempty"`
	NotManaged            bool   `protobuf:"varint,5,opt,name=not_managed,json=notManaged" json:"not_managed,omitempty"`
	ChangeManagementState string `protobuf:"bytes,6,opt,name=change_management_state,json=changeManagementState" json:"change_management_state,omitempty"`
}

func (m *InstallApplication) Reset()                    { *m = InstallApplication{} }
func (m *InstallApplication) String() string            { return proto.CompactTextString(m) }
func (*InstallApplication) ProtoMessage()               {}
func (*InstallApplication) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *InstallApplication) GetItunesStoreId() int64 {
	if m != nil {
		return m.ItunesStoreId
	}
	return 0
}

func (m *InstallApplication) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *InstallApplication) GetManifestUrl() string {
	if m != nil {
		return m.ManifestUrl
	}
	return ""
}

func (m *InstallApplication) GetManagementFlags() int64 {
	if m != nil {
		return m.ManagementFlags
	}
	return 0
}

func (m *InstallApplication) GetNotManaged() bool {
	if m != nil {
		return m.NotManaged
	}
	return false
}

func (m *InstallApplication) GetChangeManagementState() string {
	if m != nil {
		return m.ChangeManagementState
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "commandproto.Event")
	proto.RegisterType((*Payload)(nil), "commandproto.Payload")
	proto.RegisterType((*Command)(nil), "commandproto.Command")
	proto.RegisterType((*ScheduleOSUpdate)(nil), "commandproto.ScheduleOSUpdate")
	proto.RegisterType((*OSUpdate)(nil), "commandproto.OSUpdate")
	proto.RegisterType((*ScheduleOSUpdateScan)(nil), "commandproto.ScheduleOSUpdateScan")
	proto.RegisterType((*AccountConfiguration)(nil), "commandproto.AccountConfiguration")
	proto.RegisterType((*AutoSetupAdminAccounts)(nil), "commandproto.AutoSetupAdminAccounts")
	proto.RegisterType((*DeviceInformation)(nil), "commandproto.DeviceInformation")
	proto.RegisterType((*InstallProfile)(nil), "commandproto.InstallProfile")
	proto.RegisterType((*InstallApplication)(nil), "commandproto.InstallApplication")
}

func init() { proto.RegisterFile("command.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 813 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x94, 0x5b, 0x6f, 0x1b, 0x45,
	0x14, 0xc7, 0x65, 0x3b, 0x89, 0xed, 0xe3, 0xdc, 0x3a, 0x38, 0xe9, 0x22, 0xa0, 0x31, 0x1b, 0x40,
	0x29, 0x82, 0x80, 0x8a, 0xc4, 0x7b, 0xd4, 0x16, 0x11, 0x41, 0xdb, 0x30, 0xc6, 0x20, 0x1e, 0xd0,
	0x68, 0xd8, 0x19, 0xdb, 0xa3, 0xee, 0xce, 0x6c, 0xe7, 0x52, 0xe4, 0x07, 0x9e, 0xf8, 0x04, 0xbc,
	0xf1, 0xc2, 0x77, 0x45, 0x3b, 0x17, 0xc7, 0xb7, 0xbe, 0xf9, 0xfc, 0xe7, 0x3f, 0xbf, 0x73, 0xc6,
	0xe7, 0xec, 0x81, 0xa3, 0x42, 0x55, 0x15, 0x95, 0xec, 0xba, 0xd6, 0xca, 0x2a, 0x74, 0x18, 0x43,
	0x1f, 0xe5, 0x7f, 0xc1, 0xfe, 0xf3, 0xb7, 0x5c, 0x5a, 0x74, 0x0c, 0x6d, 0xc1, 0xb2, 0xd6, 0xa8,
	0x75, 0xd5, 0xc7, 0x6d, 0xc1, 0x10, 0x82, 0x3d, 0x2b, 0x2a, 0x9e, 0xb5, 0x47, 0xad, 0xab, 0x0e,
	0xf6, 0xbf, 0xd1, 0x57, 0xd0, 0xad, 0xe9, 0xa2, 0x54, 0x94, 0x65, 0x9d, 0x51, 0xeb, 0x6a, 0xf0,
	0xe4, 0xec, 0x7a, 0x15, 0x76, 0x7d, 0x17, 0x0e, 0x71, 0x72, 0xa1, 0x0b, 0x18, 0x30, 0xfe, 0x56,
	0x14, 0x9c, 0x38, 0x26, 0x58, 0xb6, 0xe7, 0xe9, 0x10, 0xa4, 0x09, 0x13, 0x2c, 0xff, 0x1d, 0xba,
	0xf1, 0x12, 0xfa, 0x18, 0x52, 0x65, 0xc4, 0xb9, 0x65, 0x29, 0x83, 0xa8, 0x4d, 0x9c, 0x60, 0x4d,
	0xfe, 0x18, 0xfa, 0xb2, 0xb6, 0xf2, 0x3f, 0x0d, 0x01, 0x4e, 0xae, 0xfc, 0xdf, 0x3d, 0xe8, 0x46,
	0xb1, 0xe1, 0x6b, 0xfe, 0xc6, 0x71, 0x63, 0x89, 0x5d, 0xd4, 0x3c, 0xf1, 0xa3, 0xf6, 0xf3, 0xa2,
	0xe6, 0xe8, 0x25, 0xa0, 0x58, 0xae, 0x90, 0x53, 0xa5, 0x2b, 0x6a, 0x85, 0x92, 0x31, 0xd5, 0xc5,
	0x7a, 0xaa, 0x67, 0xde, 0x77, 0x7b, 0x6f, 0xc3, 0x0f, 0xd8, 0xa6, 0x84, 0x9e, 0xc3, 0x89, 0x90,
	0xc6, 0xd2, 0xb2, 0x24, 0xb5, 0x56, 0x53, 0x51, 0xf2, 0xf8, 0xbf, 0x7d, 0xb8, 0x0e, 0xbb, 0x0d,
	0xa6, 0xbb, 0xe0, 0xc1, 0xc7, 0x62, 0x2d, 0x46, 0x3f, 0xc1, 0x7b, 0x09, 0x43, 0xeb, 0xba, 0x14,
	0x45, 0xa8, 0x6b, 0xcf, 0xa3, 0x46, 0x3b, 0x51, 0x37, 0xf7, 0x3e, 0x8c, 0xc4, 0x96, 0x86, 0x7e,
	0x85, 0x33, 0x5a, 0x14, 0xca, 0x49, 0x4b, 0x0a, 0x25, 0xa7, 0x62, 0xe6, 0x74, 0x80, 0xee, 0x7b,
	0x68, 0xbe, 0x0e, 0xbd, 0x09, 0xd6, 0xa7, 0xab, 0x4e, 0x3c, 0xa4, 0x3b, 0x54, 0xf4, 0x23, 0x20,
	0x53, 0xcc, 0x39, 0x73, 0x25, 0x27, 0xca, 0x10, 0x57, 0x33, 0x6a, 0x79, 0x76, 0xe0, 0xa9, 0x8f,
	0xd6, 0xa9, 0xe3, 0xe8, 0x7b, 0x35, 0x9e, 0x78, 0x17, 0x3e, 0x4d, 0x37, 0x5f, 0x99, 0xa0, 0xa0,
	0xdf, 0xe0, 0xe1, 0x36, 0x8d, 0x98, 0x82, 0xca, 0xac, 0xbb, 0xab, 0xd0, 0x4d, 0xe4, 0xb8, 0xa0,
	0x12, 0x0f, 0x37, 0xb1, 0x8d, 0x9a, 0x3f, 0x83, 0xd3, 0x4d, 0x37, 0xfa, 0x1a, 0xba, 0x21, 0x85,
	0xc9, 0x5a, 0xa3, 0xce, 0xd5, 0xe0, 0xc9, 0xf9, 0x3a, 0x7e, 0x59, 0x69, 0xb2, 0xe5, 0x18, 0x7a,
	0xcb, 0xdb, 0x17, 0x30, 0xa8, 0xb5, 0x62, 0xae, 0xb0, 0xe4, 0x35, 0x5f, 0xc4, 0xf9, 0x82, 0x28,
	0xfd, 0xc0, 0x17, 0xe8, 0x53, 0x38, 0x5e, 0xf6, 0xb1, 0x58, 0x8e, 0x56, 0x1f, 0x1f, 0xa5, 0x06,
	0x79, 0x31, 0xff, 0x02, 0x86, 0xbb, 0xde, 0x81, 0x86, 0xb0, 0x3f, 0x55, 0xba, 0x08, 0x93, 0xdb,
	0xc3, 0x21, 0xc8, 0xff, 0x6b, 0xc3, 0xf0, 0x66, 0x77, 0x27, 0x2e, 0xcd, 0x6b, 0x51, 0x93, 0x5a,
	0x8b, 0x8a, 0xea, 0x05, 0x31, 0xdc, 0xba, 0x9a, 0x2c, 0xbb, 0xae, 0x79, 0x68, 0x78, 0x80, 0x5d,
	0x34, 0xd6, 0xbb, 0xe0, 0x1c, 0x37, 0xc6, 0x84, 0x8c, 0x36, 0xf4, 0x0b, 0x3c, 0x36, 0xdc, 0xbe,
	0x03, 0x46, 0x0d, 0xd1, 0x7c, 0xe6, 0x4a, 0xaa, 0x89, 0x33, 0x5c, 0xfb, 0x67, 0xf5, 0xf0, 0xa5,
	0xe1, 0x76, 0x07, 0xf2, 0xc6, 0xe0, 0xe0, 0x9d, 0x18, 0xae, 0x11, 0x81, 0xf7, 0xa9, 0xb3, 0x2a,
	0x01, 0x59, 0x25, 0x64, 0xc2, 0x9a, 0xac, 0xe3, 0x9b, 0xf0, 0xc9, 0xc6, 0x30, 0x3a, 0xab, 0x02,
	0xaf, 0x31, 0x47, 0xa8, 0xc1, 0xe7, 0x74, 0xa7, 0x9e, 0xff, 0xd3, 0x82, 0xf3, 0xdd, 0x57, 0xd0,
	0x47, 0x00, 0x66, 0xae, 0xb4, 0x25, 0x92, 0x56, 0x69, 0x1f, 0xf4, 0xbd, 0xf2, 0x92, 0x56, 0x1c,
	0x7d, 0x00, 0xfd, 0xa9, 0x2b, 0xcb, 0x70, 0x1a, 0x3a, 0xd5, 0x6b, 0x04, 0x7f, 0x78, 0x09, 0x47,
	0x35, 0x35, 0xe6, 0x4f, 0xa5, 0x19, 0x99, 0x53, 0x33, 0xf7, 0x1f, 0xf6, 0x21, 0x3e, 0x4c, 0xe2,
	0xf7, 0xd4, 0xcc, 0xd1, 0x39, 0x1c, 0xcc, 0x05, 0x63, 0x3c, 0x7c, 0xab, 0x3d, 0x1c, 0xa3, 0xfc,
	0x4b, 0x78, 0xb0, 0xb5, 0x3f, 0x50, 0x06, 0xdd, 0x37, 0x8e, 0x6b, 0x11, 0x87, 0xaf, 0x8f, 0x53,
	0x98, 0x7f, 0x0e, 0xc7, 0xeb, 0x1b, 0xa2, 0xf1, 0xa6, 0x45, 0xdc, 0xf2, 0x79, 0x53, 0x98, 0xff,
	0xdd, 0x06, 0xb4, 0xbd, 0x03, 0xd0, 0x67, 0x70, 0x22, 0xac, 0x93, 0xdc, 0x10, 0x63, 0x95, 0xe6,
	0x24, 0xee, 0xd7, 0x0e, 0x3e, 0x0a, 0xf2, 0xb8, 0x51, 0x6f, 0x19, 0x7a, 0x04, 0x20, 0x18, 0x97,
	0x56, 0x4c, 0x45, 0xec, 0x63, 0x1f, 0xaf, 0x28, 0xcd, 0x12, 0xad, 0xa8, 0x14, 0xd3, 0x66, 0x8b,
	0x3a, 0x5d, 0xfa, 0x57, 0xf7, 0xf1, 0x20, 0x69, 0x13, 0x5d, 0xa2, 0xc7, 0x70, 0x5a, 0x51, 0x49,
	0x67, 0xbc, 0xe2, 0xd2, 0x92, 0x69, 0x49, 0x67, 0xc6, 0x3f, 0xbf, 0x83, 0x4f, 0xee, 0xf5, 0xef,
	0x1a, 0xb9, 0xf9, 0x62, 0xa4, 0xb2, 0x24, 0xc8, 0xcc, 0xef, 0x9e, 0x1e, 0x06, 0xa9, 0xec, 0x8b,
	0xa0, 0xa0, 0x6f, 0xe1, 0x61, 0x31, 0xa7, 0x72, 0xc6, 0xc9, 0x0a, 0xd2, 0xd8, 0xb4, 0x52, 0xfa,
	0xf8, 0x2c, 0x1c, 0xbf, 0x58, 0x9e, 0x8e, 0x9b, 0xc3, 0x3f, 0x0e, 0xfc, 0xa8, 0x7c, 0xf3, 0x7f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x5a, 0x6f, 0x19, 0xfb, 0x06, 0x00, 0x00,
}
