// Code generated by protoc-gen-go.
// source: device_command.proto
// DO NOT EDIT!

/*
Package devicecommandproto is a generated protocol buffer package.

It is generated from these files:
	device_command.proto

It has these top-level messages:
	Command
	DeviceCommand
*/
package devicecommandproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Command struct {
	Uuid    string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Command) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Command) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type DeviceCommand struct {
	DeviceUdid string     `protobuf:"bytes,1,opt,name=device_udid,json=deviceUdid" json:"device_udid,omitempty"`
	Commands   []*Command `protobuf:"bytes,2,rep,name=commands" json:"commands,omitempty"`
}

func (m *DeviceCommand) Reset()                    { *m = DeviceCommand{} }
func (m *DeviceCommand) String() string            { return proto.CompactTextString(m) }
func (*DeviceCommand) ProtoMessage()               {}
func (*DeviceCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeviceCommand) GetDeviceUdid() string {
	if m != nil {
		return m.DeviceUdid
	}
	return ""
}

func (m *DeviceCommand) GetCommands() []*Command {
	if m != nil {
		return m.Commands
	}
	return nil
}

func init() {
	proto.RegisterType((*Command)(nil), "devicecommandproto.Command")
	proto.RegisterType((*DeviceCommand)(nil), "devicecommandproto.DeviceCommand")
}

func init() { proto.RegisterFile("device_command.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x49, 0x2d, 0xcb,
	0x4c, 0x4e, 0x8d, 0x4f, 0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x12, 0x82, 0x88, 0x42, 0x05, 0xc1, 0x62, 0x4a, 0xe6, 0x5c, 0xec, 0xce, 0x10, 0xbe, 0x90,
	0x10, 0x17, 0x4b, 0x69, 0x69, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0x2d,
	0x24, 0xc1, 0xc5, 0x5e, 0x90, 0x58, 0x99, 0x93, 0x9f, 0x98, 0x22, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1,
	0x13, 0x04, 0xe3, 0x2a, 0x65, 0x72, 0xf1, 0xba, 0x80, 0x8d, 0x83, 0x69, 0x97, 0xe7, 0xe2, 0x86,
	0xda, 0x5a, 0x9a, 0x02, 0x37, 0x85, 0x0b, 0x22, 0x14, 0x9a, 0x92, 0x99, 0x22, 0x64, 0xce, 0xc5,
	0x01, 0xb5, 0xba, 0x58, 0x82, 0x49, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x5a, 0x0f, 0xd3, 0x45, 0x7a,
	0x50, 0xf3, 0x82, 0xe0, 0x8a, 0x93, 0xd8, 0xc0, 0x12, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x04, 0x71, 0x44, 0xf5, 0xd6, 0x00, 0x00, 0x00,
}
