// Code generated by protoc-gen-go.
// source: blueprint.proto
// DO NOT EDIT!

/*
Package blueprintproto is a generated protocol buffer package.

It is generated from these files:
	blueprint.proto

It has these top-level messages:
	Blueprint
*/
package blueprintproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Blueprint struct {
	Uuid          string   `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Name          string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	ManifestUrls  []string `protobuf:"bytes,3,rep,name=manifest_urls,json=manifestUrls" json:"manifest_urls,omitempty"`
	Mobileconfigs [][]byte `protobuf:"bytes,4,rep,name=mobileconfigs,proto3" json:"mobileconfigs,omitempty"`
}

func (m *Blueprint) Reset()                    { *m = Blueprint{} }
func (m *Blueprint) String() string            { return proto.CompactTextString(m) }
func (*Blueprint) ProtoMessage()               {}
func (*Blueprint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Blueprint) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Blueprint) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Blueprint) GetManifestUrls() []string {
	if m != nil {
		return m.ManifestUrls
	}
	return nil
}

func (m *Blueprint) GetMobileconfigs() [][]byte {
	if m != nil {
		return m.Mobileconfigs
	}
	return nil
}

func init() {
	proto.RegisterType((*Blueprint)(nil), "blueprintproto.Blueprint")
}

func init() { proto.RegisterFile("blueprint.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xca, 0x29, 0x4d,
	0x2d, 0x28, 0xca, 0xcc, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x83, 0x0b, 0x80,
	0xf9, 0x4a, 0x75, 0x5c, 0x9c, 0x4e, 0x30, 0x11, 0x21, 0x21, 0x2e, 0x96, 0xd2, 0xd2, 0xcc, 0x14,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x1b, 0x24, 0x96, 0x97, 0x98, 0x9b, 0x2a, 0xc1,
	0x04, 0x11, 0x03, 0xb1, 0x85, 0x94, 0xb9, 0x78, 0x73, 0x13, 0xf3, 0x32, 0xd3, 0x52, 0x8b, 0x4b,
	0xe2, 0x4b, 0x8b, 0x72, 0x8a, 0x25, 0x98, 0x15, 0x98, 0x35, 0x38, 0x83, 0x78, 0x60, 0x82, 0xa1,
	0x45, 0x39, 0xc5, 0x42, 0x2a, 0x5c, 0xbc, 0xb9, 0xf9, 0x49, 0x99, 0x39, 0xa9, 0xc9, 0xf9, 0x79,
	0x69, 0x99, 0xe9, 0xc5, 0x12, 0x2c, 0x0a, 0xcc, 0x1a, 0x3c, 0x41, 0xa8, 0x82, 0x49, 0x6c, 0x60,
	0x67, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xef, 0xe9, 0x3b, 0xa9, 0x00, 0x00, 0x00,
}
