// Code generated by protoc-gen-go.
// source: device.proto
// DO NOT EDIT!

/*
Package deviceproto is a generated protocol buffer package.

It is generated from these files:
	device.proto

It has these top-level messages:
	Device
*/
package deviceproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Device struct {
	Uuid                  string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Udid                  string `protobuf:"bytes,2,opt,name=udid" json:"udid,omitempty"`
	SerialNumber          string `protobuf:"bytes,3,opt,name=serial_number,json=serialNumber" json:"serial_number,omitempty"`
	OsVersion             string `protobuf:"bytes,4,opt,name=os_version,json=osVersion" json:"os_version,omitempty"`
	BuildVersion          string `protobuf:"bytes,5,opt,name=build_version,json=buildVersion" json:"build_version,omitempty"`
	ProductName           string `protobuf:"bytes,6,opt,name=product_name,json=productName" json:"product_name,omitempty"`
	Imei                  string `protobuf:"bytes,7,opt,name=imei" json:"imei,omitempty"`
	Meid                  string `protobuf:"bytes,8,opt,name=meid" json:"meid,omitempty"`
	Token                 string `protobuf:"bytes,9,opt,name=token" json:"token,omitempty"`
	PushMagic             string `protobuf:"bytes,10,opt,name=push_magic,json=pushMagic" json:"push_magic,omitempty"`
	MdmTopic              string `protobuf:"bytes,11,opt,name=mdm_topic,json=mdmTopic" json:"mdm_topic,omitempty"`
	UnlockToken           string `protobuf:"bytes,12,opt,name=unlock_token,json=unlockToken" json:"unlock_token,omitempty"`
	Enrolled              bool   `protobuf:"varint,13,opt,name=enrolled" json:"enrolled,omitempty"`
	AwaitingConfiguration bool   `protobuf:"varint,14,opt,name=awaiting_configuration,json=awaitingConfiguration" json:"awaiting_configuration,omitempty"`
	DeviceName            string `protobuf:"bytes,15,opt,name=device_name,json=deviceName" json:"device_name,omitempty"`
	Model                 string `protobuf:"bytes,16,opt,name=model" json:"model,omitempty"`
	ModelName             string `protobuf:"bytes,17,opt,name=model_name,json=modelName" json:"model_name,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Device) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Device) GetUdid() string {
	if m != nil {
		return m.Udid
	}
	return ""
}

func (m *Device) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *Device) GetOsVersion() string {
	if m != nil {
		return m.OsVersion
	}
	return ""
}

func (m *Device) GetBuildVersion() string {
	if m != nil {
		return m.BuildVersion
	}
	return ""
}

func (m *Device) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *Device) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *Device) GetMeid() string {
	if m != nil {
		return m.Meid
	}
	return ""
}

func (m *Device) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Device) GetPushMagic() string {
	if m != nil {
		return m.PushMagic
	}
	return ""
}

func (m *Device) GetMdmTopic() string {
	if m != nil {
		return m.MdmTopic
	}
	return ""
}

func (m *Device) GetUnlockToken() string {
	if m != nil {
		return m.UnlockToken
	}
	return ""
}

func (m *Device) GetEnrolled() bool {
	if m != nil {
		return m.Enrolled
	}
	return false
}

func (m *Device) GetAwaitingConfiguration() bool {
	if m != nil {
		return m.AwaitingConfiguration
	}
	return false
}

func (m *Device) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *Device) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Device) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func init() {
	proto.RegisterType((*Device)(nil), "deviceproto.Device")
}

func init() { proto.RegisterFile("device.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x92, 0xc1, 0x4f, 0x2a, 0x31,
	0x10, 0xc6, 0xc3, 0x7b, 0xc0, 0xdb, 0x1d, 0x96, 0xf7, 0x9e, 0x0d, 0x9a, 0x46, 0x63, 0x44, 0xbd,
	0x70, 0xf2, 0x62, 0xfc, 0x0b, 0xf4, 0x2a, 0x07, 0x42, 0xbc, 0x36, 0x65, 0x5b, 0x71, 0xc2, 0xb6,
	0xdd, 0x74, 0xb7, 0x78, 0xf7, 0x2f, 0x37, 0x9d, 0x01, 0xe2, 0x6d, 0xbe, 0xdf, 0x7c, 0x1d, 0xbe,
	0x19, 0x16, 0x2a, 0x63, 0xf7, 0x58, 0xdb, 0x87, 0x36, 0x86, 0x3e, 0x88, 0x09, 0x2b, 0x12, 0x77,
	0x5f, 0x43, 0x18, 0xbf, 0x90, 0x16, 0x02, 0x86, 0x29, 0xa1, 0x91, 0x83, 0xf9, 0x60, 0x51, 0xae,
	0xa8, 0x26, 0x66, 0xd0, 0xc8, 0x5f, 0x07, 0x66, 0xd0, 0x88, 0x7b, 0x98, 0x76, 0x36, 0xa2, 0x6e,
	0x94, 0x4f, 0x6e, 0x63, 0xa3, 0xfc, 0x4d, 0xcd, 0x8a, 0xe1, 0x92, 0x98, 0xb8, 0x06, 0x08, 0x9d,
	0xda, 0xdb, 0xd8, 0x61, 0xf0, 0x72, 0x48, 0x8e, 0x32, 0x74, 0x6f, 0x0c, 0xf2, 0x8c, 0x4d, 0xc2,
	0xc6, 0x9c, 0x1c, 0x23, 0x9e, 0x41, 0xf0, 0x68, 0xba, 0x85, 0xaa, 0x8d, 0xc1, 0xa4, 0xba, 0x57,
	0x5e, 0x3b, 0x2b, 0xc7, 0xe4, 0x99, 0x1c, 0xd8, 0x52, 0x3b, 0xca, 0x8c, 0xce, 0xa2, 0xfc, 0xc3,
	0xf9, 0x72, 0x9d, 0x99, 0xb3, 0x68, 0x64, 0xc1, 0x2c, 0xd7, 0x62, 0x06, 0xa3, 0x3e, 0xec, 0xac,
	0x97, 0x25, 0x41, 0x16, 0x39, 0x64, 0x9b, 0xba, 0x0f, 0xe5, 0xf4, 0x16, 0x6b, 0x09, 0x1c, 0x32,
	0x93, 0xd7, 0x0c, 0xc4, 0x15, 0x94, 0xce, 0x38, 0xd5, 0x87, 0x16, 0x6b, 0x39, 0xa1, 0x6e, 0xe1,
	0x8c, 0x5b, 0x67, 0x9d, 0xc3, 0x25, 0xdf, 0x84, 0x7a, 0xa7, 0x78, 0x70, 0xc5, 0xe1, 0x98, 0xad,
	0x69, 0xfc, 0x25, 0x14, 0xd6, 0xc7, 0xd0, 0x34, 0xd6, 0xc8, 0xe9, 0x7c, 0xb0, 0x28, 0x56, 0x27,
	0x2d, 0x9e, 0xe0, 0x42, 0x7f, 0x6a, 0xec, 0xd1, 0x6f, 0x55, 0x1d, 0xfc, 0x3b, 0x6e, 0x53, 0xd4,
	0x7d, 0xbe, 0xc4, 0x5f, 0x72, 0x9e, 0x1f, 0xbb, 0xcf, 0x3f, 0x9b, 0xe2, 0x06, 0x0e, 0xff, 0x1e,
	0x5f, 0xe4, 0x1f, 0xfd, 0x28, 0x30, 0xa2, 0x83, 0xcc, 0x60, 0xe4, 0x82, 0xb1, 0x8d, 0xfc, 0xcf,
	0x8b, 0x92, 0xc8, 0x8b, 0x52, 0xc1, 0xaf, 0xce, 0x78, 0x51, 0x22, 0xf9, 0xd1, 0x66, 0x4c, 0xdf,
	0xc2, 0xe3, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0xf1, 0x34, 0x8f, 0x28, 0x02, 0x00, 0x00,
}
