#!/bin/bash

source $MICROMDM_ENV_PATH
micromdm="$(pwd)/build/$(uname |tr [:upper:] [:lower:])/micromdm"
config_root="$(pwd)/tools/ngrok/config_root"
mkdir -p $config_root

$micromdm serve \
  -api-key $API_TOKEN \
  -server-url=$SERVER_URL \
  -config-path $config_root \
  -tls=false "$@"
